version: '3.8'

services:
  backend:
    environment:
      FLASK_ENV: production  # Set production environment
      DATABASE_URL: postgresql://user:password@db:5432/market_engine
      SELENIUM_DRIVER_NAME: chrome
      SELENIUM_DRIVER_EXECUTABLE_PATH: http://selenium:4444/wd/hub  # Same as in development

  db:
    volumes:
      - db-data:/var/lib/postgresql/data  # Ensure persistent database storage

  selenium:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"  # Logging restrictions to avoid excessive log files
