# Use the official PostgreSQL image
FROM postgres:13-alpine

# Set environment variables for PostgreSQL
ENV POSTGRES_USER=user
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=market_engine_db

# Expose the default PostgreSQL port
EXPOSE 5432